### ISSUE TITLE
requester.TestTracer occasionally fails

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#37]
## Description

⚠️ WIP

see https://github.com/benchttp/runner/runs/5065678069?check_suite_focus=true

**Comment by moreirathomas** [comment]
As suggested earlier today in person: 

This results from the fact that we expect trace events to happen sequentially with at least 1 nanosecond between them. It seems to not always be true (inner arcanes of the machine).

What we could do to fix the faulty test:
- expect that the events happen sequentially but only refuse going in the past: `time1 >= time0` instead of `time1 > time0`
- at the end verify that the trace took non-zero time: `timeN > time0`
- if both are true, then the trace events happened in a sequence increasing at least linearly, which is enough for our test case
