### ISSUE TITLE
Handle huge Report payload sent to benchttp server

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#62]
## Description

We don't want to allow any report size to be sent to benchttp server.

## Tasks

- [ ] Determine the most relevant strategy to avoid sending huge reports (UX matters)
- [ ] Validate the solution with the team and implement it

## Suggestions

Some non mutually exclusive ideas:
- Check the length of gob-encoded `output.Output` and return an error if it's too big
- Check the length of `Report.Records` in `output` and return an error if it's too big
- Check the length of `Report.Records` during the run and stop if it's too big
- Do not record all requests made but only _some_ of them (regularly spaced, like a comb)
- Set a maximum value for `config.Runner.Requests` (then `-1` should fallback to that value)

## Notes

- Blocked by https://github.com/benchttp/server/issues/19

**Comment by GregoryAlbouy** [comment]
For reference: JSON files sizes depending on total requets

| Number of requests | Indented JSON (default) | Compressed JSON
| ---: | :---: | :---: |
| 100 | `64kB`
| 1000 | `625KB`
| 10000 | `5.8MB` | `2.5MB`
| 100000 | `58MB` | `25MB`
| 1000000 | `577MB` | `250MB`

**Comment by GregoryAlbouy** [comment]
Specs proposal:

🚧  WIP


## Config changes

None. No max requests validation upstream at the config level

## Requester implementation

- Define a max requests number to be **_recorded_**
- This value should be fixed to a value between `1000` and `10000`
- Always **_run_** the exact number of requests required by user: do not cap it
- The algorithm should record requests with an equal repartition
e.g.: if `requests == 20000` and `maxRecordedRequests == 5000`, record 1 request out of 4 
- `Report.Length` should still reflect the number of recorded requests `len(Report.Records)`
- Add new field `Report.Count` (name to be discussed) that reflects the total number requests run (e.g. equal to `cfg.Runner.Requests` but not necessarily if timeout/canceled or if `requests == -1`)

**Comment by moreirathomas** [comment]
Several thoughts.

Limiting is server side:
- I think limiting the max recorded requests length belongs to the server, the runner does not deal with _accepting_ to process the data server side (our api and the data store)
- it may be something like a reverse proxy/load balancer with body content length validation

User-friendly UX runner side is required:
- now I agree that UX-wise `runner` should do something about it to not fool the user in sending a report that triggers a bad request
- what you suggest with the "comb" solution is nice but is weird if the output strategy is not `benchttp` because writing to a json file locally should not come with server-side limitation
- thus if we allow to make any specified amount of requests, only sending to the server should be limited

This seems a bit more complex, what I suggest to do in runner as the less effort intensive implementation:
- when exporting to the server, fail if body size is greater than an arbitrary constant
- propose to export to json as a fallback via cli (similarly to the ctrl+c handling)

**Comment by GregoryAlbouy** [comment]
> - when exporting to the server, fail if body size is greater than an arbitrary constant
> - propose to export to json as a fallback via cli (similarly to the ctrl+c handling)

I suggested a similar option in Discord with a small difference:

1. implement body size validation server-side
2. no spec changes in config or requester, export to benchttp as usual except now server returns a bad status code if necessary
3. prompt to suggest a fallback

**Comment by GregoryAlbouy** [comment]
Note: this version has a considerable advantage over the "comb" version: it handles infinite requests as well as fixed requests. The "comb" version needs to know the number of requests in advance and it would be complex to estimate it if not explicitly given.

**Comment by GregoryAlbouy** [comment]
Closed by #72
